### ISSUE TITLE
Illegal Characters in Chat

### ISSUE THREAD

**Issue by rcmaehl** [Draylar/mycolor#6]
I believe this mod may be incompatible with bungeecord or some other part of the bungeecord setup. Attemtping to use it in chat kicks me to lobby with the Vanilla Minecraft error of: "Illegal characters in chat"

![image](https://user-images.githubusercontent.com/716581/91323859-6049a480-e78f-11ea-88ad-05b6146f5364.png)

**Comment by Draylar** [comment]
Is Color Unchained installed on the Bungeecord server?

**Comment by rcmaehl** [comment]
No, it's not listed as a requirement in the CurseForge page.

**Comment by Draylar** [comment]
Updated the CF page to clarify. Yes, the mod is required on the client and server, as the vanilla server rejects all chat messages with special formatting symbols in them. This mod nukes those checks to prevent clients from being kicked. Let me know if you have any other questions, thanks for the report.
