### ISSUE TITLE
Update to 1.16.2 and 1.16.3

### ISSUE THREAD

**Issue by SolidBlock-cn** [Draylar/mycolor#7]
Although installing 1.16.1ver mod for 1.16.2 is possible, yet clicking the button causes crash. Please update the mod to 1.16.2 and 1.16.3.

**Comment by Mhowser** [comment]
Please @Draylar

**Comment by SolidBlock-cn** [comment]
Please update. @Draylar

**Comment by Draylar** [comment]
Feel free to PR an update if you want it now, I am busy at the moment and am aware of the issue

**Comment by Draylar** [comment]
seemed to just require a rebuild in newer versions, fixed in 1.1.1 jar build on GH/CF

**Comment by SolidBlock-cn** [comment]
Does not work when editing a sign.
Directly inputing § does not work.
Causes crash when sending messages with a §, and NotEnoughCrashes reports that this crash may be associated with LambDynamicLight and VoxelMap.
